=== unmetro/4to-Semestre-Ciencia-de-Datos/Desarollo_de_Aplicaciones_Web/practica DTD/ejercicio1/ejercicio1.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor, fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (nombre, fechaNacimiento?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT fechaPublicacion EMPTY>
<!ATTLIST fechaPublicacion aÃ±o CDATA #REQUIRED>

=== unmetro/4to-Semestre-Ciencia-de-Datos/Desarollo_de_Aplicaciones_Web/practica DTD/ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ejercicio1.xsl"?>
<!DOCTYPE biblioteca SYSTEM "ejercicio1.dtd">
<biblioteca>
    <libro>
        <titulo>La vida está en otra parte</titulo>
        <autor>
            <nombre>Milan Kundera</nombre>
        </autor>
        <fechaPublicacion año="1973"/>
    </libro>
    <libro>
        <titulo>Pantaleón y las visitadoras</titulo>
        <autor>
            <nombre>Mario Vargas Llosa</nombre>
            <fechaNacimiento>26/03/1936</fechaNacimiento>
        </autor>
        <fechaPublicacion año="1973"/>
    </libro>
    <libro>
        <titulo>Conversación en la catedral</titulo>
        <autor>
            <nombre>Mario Vargas Llosa</nombre>
            <fechaNacimiento>26/03/1936</fechaNacimiento>
        </autor>
        <fechaPublicacion año="1969"/>
    </libro>
</biblioteca>
